# Generated by Django 3.1.3 on 2021-01-04 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201221_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reviewed_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='score',
            field=models.FloatField(default=100.0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=255)),
                ('review_score', models.FloatField(default=0.0)),
                ('review_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='accounts.customuser')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='accounts.customuser')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
