# Generated by Django 3.1.3 on 2021-01-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210104_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend_code',
            field=models.CharField(default='0C9C0A201D', max_length=50, unique=True),
        ),
    ]
