# Generated by Django 3.1.3 on 2021-01-04 05:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_friend_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friend_code',
            field=models.CharField(default=accounts.models.fc_generator, max_length=50, unique=True),
        ),
    ]
