# Generated by Django 3.1.3 on 2020-12-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
