# Generated by Django 3.1.3 on 2020-12-24 06:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20201221_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_vector', 'message_vector'],
                                                           name='Post_title_v_668609_gin'),
        ),

        migrations.RunSQL(
            '''
            CREATE TRIGGER title_vector_update BEFORE INSERT OR UPDATE
            ON Post FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger('title_vector', 'pg_catalog.english', 'title');
            ''',
        ),

        migrations.RunSQL(
            '''
            CREATE TRIGGER message_vector_update BEFORE INSERT OR UPDATE
            ON Post FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger('message_vector', 'pg_catalog.english', 'message');
            ''',
        ),
    ]
