# Generated by Django 3.1.3 on 2020-12-24 06:40

import django.contrib.postgres.search
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201221_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
        TrigramExtension(),
    ]
