# Generated by Django 3.1.3 on 2021-01-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201224_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='search_vector',
        ),
    ]
